apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginxchart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nginxchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    {{- include "nginxchart.selectorLabels" . | nindent 4 }}
